/**:
  ros__parameters:
    wheel_radius: 0.315 #0.3935
    wheel_width: 0.1
    wheel_base: 2.64 # between front wheel center and rear wheel center
    wheel_tread: 1.75 # between left wheel center and right wheel center
    front_overhang: 0.99  # between front wheel center and vehicle front
    rear_overhang: 0.81 # between rear wheel center and vehicle rear
    left_overhang: 0.14  # between left wheel center and vehicle left
    right_overhang: 0.14  # between right wheel center and vehicle right
    vehicle_height: 1.86
    max_steer_angle: 0.6105 # [rad] check again!(temp)
