/**:
  ros__parameters:
    input_frame: "base_link"
    output_frame: "base_link"
    min_x: -150.0
    max_x: 150.0
    min_y: -150.0
    max_y: 150.0
    min_z: -30.0
    max_z: 100.0
    negative: False
